/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.projetofarmacia.interfaces;

import com.projetofarmacia.DAO.ProdutoDAO;
import java.awt.Color;
import java.util.List;
import java.text.SimpleDateFormat;
import com.projetofarmacia.javabeans.Produto;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Calendoscopio
 */
public class ConsultarProduto extends javax.swing.JInternalFrame {
    private static final long serialVersionUID = 1L;

    /**
     * Creates new form consutarProduto
     */
    public ConsultarProduto() {
        initComponents();
       //  -----------------------------------------------------
            ScrollPane.setOpaque(false);
            ScrollPane.getViewport().setOpaque(false);
            tabelaProdutos.setOpaque(false);
            tabelaProdutos.setBackground(new Color(255, 255, 255, 0));
        //    ---------------------------------------------------
      //  ImageIcon icon = new ImageIcon("src/recursos/logo.png");
       //logo2.setIcon(icon);
       // icon.setImage(icon.getImage().getScaledInstance(logo2.getWidth(), 
        //        logo2.getHeight(), Image.SCALE_DEFAULT));
       // logo2.setIcon(icon);
        
        
        //-------------------------------------------------------
    }
    public void Listar() {
        try {
            ProdutoDAO dao = new ProdutoDAO();
            List<Produto> listaDeProdutos = dao.listarProduto();
            
            DefaultTableModel modelo = (DefaultTableModel) tabelaProdutos.getModel();
            modelo.setNumRows(0);
            
            for (Produto p: listaDeProdutos) {
                modelo.addRow(new Object[] {
                    p.getIdProduto(),
                    p.getNomeProduto(),
                    p.getFornecedor(),
                    p.getQuantidade(),
                    p.getTarja(),
                    p.getPreco(),
                    new SimpleDateFormat("dd/MM/yyyy").format(p.getDataValidade()),
                    new SimpleDateFormat("dd/MM/yyyy").format(p.getDataFabricacao()),
                    p.getFarmacia().getIdFarmacia(),
                    p.getLote(),
                    p.getStatus(),
                    p.getTipoProduto().getIdTipoProduto(),
                    p.getCodigoBarras()
                });
            }
        } catch (Exception e) {
            System.out.println("erro" + e);
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEditar = new javax.swing.JButton();
        btnProcurar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ScrollPane = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();

        setBackground(new java.awt.Color(52, 152, 219));
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consultar Produto");
        setFocusable(false);
        setVisible(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(52, 152, 219));

        btnEditar.setBackground(new java.awt.Color(52, 152, 219));
        btnEditar.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/projetofarmacia/resources/product-edit.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnProcurar.setBackground(new java.awt.Color(52, 152, 219));
        btnProcurar.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        btnProcurar.setForeground(new java.awt.Color(255, 255, 255));
        btnProcurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/projetofarmacia/resources/Folder Search-certo.png"))); // NOI18N
        btnProcurar.setText("Procurar");

        jTextField1.setBackground(new java.awt.Color(52, 152, 219));
        jTextField1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField1.setCaretColor(new java.awt.Color(52, 152, 219));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Consultar Produto");

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome");

        tabelaProdutos.setForeground(new java.awt.Color(255, 255, 255));
        tabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Fornecedor", "Quantidade", "Tarja", "Preço", "Data de Validade", "Data de Fabricação", "Farmácia", "lote", "reserva", "tipo", "Codbar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaProdutos.setGridColor(new java.awt.Color(51, 102, 255));
        tabelaProdutos.setSurrendersFocusOnKeystroke(true);
        tabelaProdutos.getTableHeader().setResizingAllowed(false);
        tabelaProdutos.getTableHeader().setReorderingAllowed(false);
        ScrollPane.setViewportView(tabelaProdutos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnProcurar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        Listar();
    }//GEN-LAST:event_formInternalFrameActivated

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        try {
            if (tabelaProdutos.getSelectedRow() == -1) {
                System.out.println("EEEERRRRO");
            } else {
                CadastroProduto cp = new CadastroProduto();
                cp.listarProdutos(Integer.parseInt(tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 0).toString()), 
                        tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 1).toString(),
                        tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 2).toString(),
                        Integer.parseInt(tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 3).toString()),
                        tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 4).toString(), 
                        Double.parseDouble(tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 5).toString()),
                        new SimpleDateFormat("dd/MM/yyyy").parse(tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 6).toString()),
                        new SimpleDateFormat("dd/MM/yyyy").parse(tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 7).toString()),
                        tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 8).toString(),
                        (tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 9).toString())
                        /*(tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 10).toString())*/);
                
                TelaEstoquista.painel.add(cp);
                cp.setVisible(true);
                
                Object[] obj = cp.recuperaDados();
                for (int i = 0; i < obj.length && i < tabelaProdutos.getColumnCount(); i++) {
                    tabelaProdutos.setValueAt(obj[i], tabelaProdutos.getSelectedRow(), i);
                }
            }
        } catch (ParseException | NullPointerException e) {
            Logger.getLogger(ConsultarProduto.class.getName()).log(Level.SEVERE, null, e);
            System.out.println("erro " + e);
        }
        
    }//GEN-LAST:event_btnEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnProcurar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tabelaProdutos;
    // End of variables declaration//GEN-END:variables
}
