/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.projetofarmacia.interfaces;

import com.projetofarmacia.DAO.ProdutoDAO;
import com.projetofarmacia.dialogs.confirmarExclusaoProd;
import com.projetofarmacia.dialogs.consultaProduto;
import com.projetofarmacia.dialogs.selecioneTabela;
import com.projetofarmacia.javabeans.Farmacia;
import java.awt.Color;
import java.util.List;
import java.text.SimpleDateFormat;
import com.projetofarmacia.javabeans.Produto;
import java.awt.HeadlessException;
import java.awt.Point;
import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Calendoscopio
 */
public class ConsultarProduto extends javax.swing.JInternalFrame {
    private static final long serialVersionUID = 1L;
    public static boolean isEditing;

    /**
     * Creates new form consutarProduto
     */
    public ConsultarProduto() {
        initComponents();
        if (TelaLogin.idFunc == 1) {
            btnEditar.setEnabled(false);
            btnEditar.setVisible(false);
        }
       //  -----------------------------------------------------
            ScrollPane.setOpaque(false);
            ScrollPane.getViewport().setOpaque(false);
            tabelaProdutos.setOpaque(false);
            tabelaProdutos.setBackground(new Color(255, 255, 255, 0));
        //    ---------------------------------------------------
      //  ImageIcon icon = new ImageIcon("src/recursos/logo.png");
       //logo2.setIcon(icon);
       // icon.setImage(icon.getImage().getScaledInstance(logo2.getWidth(), 
        //        logo2.getHeight(), Image.SCALE_DEFAULT));
       // logo2.setIcon(icon);
        
        
        //-------------------------------------------------------
    }
    public void Listar() {
        try {
            Farmacia far = new Farmacia();
            far.setIdFarmacia(TelaLogin.idFar);
            ProdutoDAO dao = new ProdutoDAO();
            List<Produto> listaDeProdutos = dao.listarProduto(far);
            DefaultTableModel modelo = (DefaultTableModel) tabelaProdutos.getModel();
            modelo.setNumRows(0);
            
            for (Produto p: listaDeProdutos) {
                modelo.addRow(new Object[] {
                    p.getIdProduto(),
                    p.getNomeProduto(),
                    p.getFornecedor(),
                    p.getQuantidade(),
                    p.getTarja(),
                    p.getPreco(),
                    new SimpleDateFormat("dd/MM/yyyy").format(p.getDataValidade()),
                    new SimpleDateFormat("dd/MM/yyyy").format(p.getDataFabricacao()),
                    p.getFarmacia().getNomeFarmacia(),
                    p.getLote(),
                    p.getStatus(),
                    p.getTipoProduto().getTipoProduto(),
                    p.getCodigoBarras()
                });
            }
        } catch (Exception e) {
            System.out.println("erro" + e);
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEditar = new javax.swing.JButton();
        btnProcurar = new javax.swing.JButton();
        campoNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ScrollPane = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();

        setBackground(new java.awt.Color(52, 152, 219));
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consultar Produto");
        setFocusable(false);
        setVisible(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(52, 152, 219));

        btnEditar.setBackground(new java.awt.Color(52, 152, 219));
        btnEditar.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/projetofarmacia/resources/product-edit.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnProcurar.setBackground(new java.awt.Color(52, 152, 219));
        btnProcurar.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        btnProcurar.setForeground(new java.awt.Color(255, 255, 255));
        btnProcurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/projetofarmacia/resources/Folder Search-certo.png"))); // NOI18N
        btnProcurar.setText("Procurar");

        campoNome.setBackground(new java.awt.Color(52, 152, 219));
        campoNome.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        campoNome.setForeground(new java.awt.Color(255, 255, 255));
        campoNome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        campoNome.setCaretColor(new java.awt.Color(52, 152, 219));
        campoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeActionPerformed(evt);
            }
        });
        campoNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoNomeKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Consultar Produto");

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome");

        tabelaProdutos.setForeground(new java.awt.Color(255, 255, 255));
        tabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Fornecedor", "Quantidade", "Tarja", "Preço", "Data de Validade", "Data de Fabricação", "Farmácia", "lote", "reserva", "tipo", "Codbar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaProdutos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tabelaProdutos.setGridColor(new java.awt.Color(51, 102, 255));
        tabelaProdutos.setSurrendersFocusOnKeystroke(true);
        tabelaProdutos.getTableHeader().setResizingAllowed(false);
        tabelaProdutos.getTableHeader().setReorderingAllowed(false);
        tabelaProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabelaProdutosMousePressed(evt);
            }
        });
        ScrollPane.setViewportView(tabelaProdutos);
        if (tabelaProdutos.getColumnModel().getColumnCount() > 0) {
            tabelaProdutos.getColumnModel().getColumn(0).setMinWidth(0);
            tabelaProdutos.getColumnModel().getColumn(0).setPreferredWidth(0);
            tabelaProdutos.getColumnModel().getColumn(0).setMaxWidth(0);
            tabelaProdutos.getColumnModel().getColumn(9).setMinWidth(0);
            tabelaProdutos.getColumnModel().getColumn(9).setPreferredWidth(0);
            tabelaProdutos.getColumnModel().getColumn(9).setMaxWidth(0);
            tabelaProdutos.getColumnModel().getColumn(10).setMinWidth(0);
            tabelaProdutos.getColumnModel().getColumn(10).setPreferredWidth(0);
            tabelaProdutos.getColumnModel().getColumn(10).setMaxWidth(0);
            tabelaProdutos.getColumnModel().getColumn(11).setMinWidth(0);
            tabelaProdutos.getColumnModel().getColumn(11).setPreferredWidth(0);
            tabelaProdutos.getColumnModel().getColumn(11).setMaxWidth(0);
            tabelaProdutos.getColumnModel().getColumn(12).setMinWidth(0);
            tabelaProdutos.getColumnModel().getColumn(12).setPreferredWidth(0);
            tabelaProdutos.getColumnModel().getColumn(12).setMaxWidth(0);
        }

        btnExcluir.setBackground(new java.awt.Color(52, 152, 219));
        btnExcluir.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/projetofarmacia/resources/product-delete.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(campoNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnProcurar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluir)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        Listar();
    }//GEN-LAST:event_formInternalFrameActivated

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        try {
            if (tabelaProdutos.getSelectedRow() == -1) {
                System.out.println("EEEERRRRO");
            } else {
                CadastroProduto cp = new CadastroProduto();
                isEditing = true;
                cp.listarProdutos(Integer.parseInt(tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 0).toString()), 
                        tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 1).toString(),
                        tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 2).toString(),
                        Integer.parseInt(tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 3).toString()),
                        tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 4).toString(), 
                        Double.parseDouble(tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 5).toString()),
                        tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 6).toString(),
                        tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 7).toString(),
                        tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 8).toString(),
                        tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 9).toString(),
                        tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 11).toString(),
                        Long.parseLong(tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 12).toString()),
                        isEditing);
            
                TelaEstoquista.painel.add(cp);
                cp.setVisible(true);
                
                Object[] obj = cp.recuperaDados();
                for (int i = 0; i < obj.length && i < tabelaProdutos.getColumnCount(); i++) {
                    tabelaProdutos.setValueAt(obj[i], tabelaProdutos.getSelectedRow(), i);
                }
            }
            
        } catch (NullPointerException e) {
            throw new RuntimeException(e);
        }
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered

    }//GEN-LAST:event_formMouseEntered

    private void tabelaProdutosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProdutosMousePressed
        Point ponteiro = evt.getPoint();
        int linha = tabelaProdutos.rowAtPoint(ponteiro);
        if (evt.getClickCount() == 2 && tabelaProdutos.getSelectedRow() != -1) {
            new consultaProduto(null, true).setVisible(true);
        }

    }//GEN-LAST:event_tabelaProdutosMousePressed

    public static void excluirProduto() {
        try {
            Produto obj = new Produto();
            obj.setIdProduto(Integer.parseInt(ConsultarProduto.tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 0).toString()));
            ProdutoDAO dao = new ProdutoDAO();
            
            dao.excluirProduto(obj);
            dao.corrigeId();
            
//            this.dispose();
        } catch (NumberFormatException | HeadlessException e) {
            System.out.println(e);
        }
    }
    public void Buscar(String nome) {
        try {
            Farmacia far = new Farmacia();
            far.setIdFarmacia(TelaLogin.idFar);
            ProdutoDAO dao = new ProdutoDAO();
            List<Produto> listaDeProdutos = dao.buscarProduto(nome, far);
            DefaultTableModel modelo = (DefaultTableModel) tabelaProdutos.getModel();
            modelo.setNumRows(0);
            
            for (Produto p: listaDeProdutos) {
                modelo.addRow(new Object[] {
                    p.getIdProduto(),
                    p.getNomeProduto(),
                    p.getFornecedor(),
                    p.getQuantidade(),
                    p.getTarja(),
                    p.getPreco(),
                    new SimpleDateFormat("dd/MM/yyyy").format(p.getDataValidade()),
                    new SimpleDateFormat("dd/MM/yyyy").format(p.getDataFabricacao()),
                    p.getFarmacia().getNomeFarmacia(),
                    p.getLote(),
                    p.getStatus(),
                    p.getTipoProduto().getTipoProduto(),
                    p.getCodigoBarras()
                });
            }
        } catch (Exception e) {
            System.out.println("erro" + e);
            e.printStackTrace();
        }
        
    }
    private void campoNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNomeKeyReleased
        if (evt.getKeyCode() != KeyEvent.VK_ALPHANUMERIC) {
                    Buscar(campoNome.getText());
        }
    }//GEN-LAST:event_campoNomeKeyReleased

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (tabelaProdutos.getSelectedRow() == -1) {
            new selecioneTabela(null, true).setVisible(true);
        } else {
            confirmarExclusaoProd ce = new confirmarExclusaoProd(null, true);
            ce.setVisible(true);
            Listar();
            
        }
    }//GEN-LAST:event_btnExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnProcurar;
    private javax.swing.JTextField campoNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTable tabelaProdutos;
    // End of variables declaration//GEN-END:variables
}
