/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.projetofarmacia.interfaces;

import com.projetofarmacia.DAO.FuncionarioDAO;
import com.projetofarmacia.DAO.ProdutoDAO;
import com.projetofarmacia.dialogs.nenhumaLinha;
import com.projetofarmacia.javabeans.Farmacia;
import com.projetofarmacia.javabeans.Funcionario;
import com.projetofarmacia.javabeans.Produto;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Calendoscopio
 */
public class TelaFarmaceutico extends javax.swing.JFrame {
    private static Carrinho car = new Carrinho();
    /**
     * Creates new form telaprincipalAdm
     */
    public TelaFarmaceutico() {
        initComponents();
        TelaFarmaceutico.this.setExtendedState(TelaFarmaceutico.MAXIMIZED_BOTH);
        //this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("logocerto (2).png")).getImage());
       // ImageIcon icon = new ImageIcon("src/recursos/logo_barra.png");
        //barra.setIcon(icon);
        //icon.setImage(icon.getImage().getScaledInstance(barra.getWidth(), barra.getHeight(), Image.SCALE_DEFAULT));
        //barra.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        btnProcurar = new javax.swing.JButton();
        campoNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ScrollPane = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();
        btnCarrinho02 = new javax.swing.JButton();
        btnCarrinho = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        menuReservados = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Farmacia");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(52, 152, 219));

        btnProcurar.setBackground(new java.awt.Color(52, 152, 219));
        btnProcurar.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        btnProcurar.setForeground(new java.awt.Color(255, 255, 255));
        btnProcurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/projetofarmacia/resources/Folder Search-certo.png"))); // NOI18N
        btnProcurar.setText("Procurar");
        btnProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarActionPerformed(evt);
            }
        });

        campoNome.setBackground(new java.awt.Color(52, 152, 219));
        campoNome.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        campoNome.setForeground(new java.awt.Color(255, 255, 255));
        campoNome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        campoNome.setCaretColor(new java.awt.Color(52, 152, 219));
        campoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeActionPerformed(evt);
            }
        });
        campoNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoNomeKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Consultar Produto");

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome");

        tabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id*", "Nome", "Fornecedor", "Qtd", "Tarja", "Preço", "Data de Validade", "Data de Fabricação", "Farmacia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaProdutos.setGridColor(new java.awt.Color(51, 102, 255));
        tabelaProdutos.setSurrendersFocusOnKeystroke(true);
        tabelaProdutos.getTableHeader().setResizingAllowed(false);
        tabelaProdutos.getTableHeader().setReorderingAllowed(false);
        ScrollPane.setViewportView(tabelaProdutos);
        if (tabelaProdutos.getColumnModel().getColumnCount() > 0) {
            tabelaProdutos.getColumnModel().getColumn(0).setMinWidth(0);
            tabelaProdutos.getColumnModel().getColumn(0).setPreferredWidth(0);
            tabelaProdutos.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        btnCarrinho02.setBackground(new java.awt.Color(52, 152, 219));
        btnCarrinho02.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        btnCarrinho02.setForeground(new java.awt.Color(255, 255, 255));
        btnCarrinho02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/projetofarmacia/resources/basket_1.png"))); // NOI18N
        btnCarrinho02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarrinho02ActionPerformed(evt);
            }
        });

        btnCarrinho.setBackground(new java.awt.Color(52, 152, 219));
        btnCarrinho.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        btnCarrinho.setForeground(new java.awt.Color(255, 255, 255));
        btnCarrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/projetofarmacia/resources/basket_put.png"))); // NOI18N
        btnCarrinho.setText("Carrinho");
        btnCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarrinhoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ScrollPane)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 854, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProcurar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCarrinho))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCarrinho02)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnCarrinho02)
                .addGap(1, 1, 1)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout paneLayout = new javax.swing.GroupLayout(pane);
        pane.setLayout(paneLayout);
        paneLayout.setHorizontalGroup(
            paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        paneLayout.setVerticalGroup(
            paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pane.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenuBar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        menuReservados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/projetofarmacia/resources/delivery.png"))); // NOI18N
        menuReservados.setText("Reservados ");
        menuReservados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuReservadosMouseClicked(evt);
            }
        });
        menuReservados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReservadosActionPerformed(evt);
            }
        });
        jMenuBar2.add(menuReservados);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void adicionarCarrinho() {
        DefaultTableModel tabelaOrigem = (DefaultTableModel) tabelaProdutos.getModel();
        DefaultTableModel tabelaDestino = (DefaultTableModel) Carrinho.tabelaCarrinho.getModel();
        Funcionario f = new Funcionario();
        FuncionarioDAO dao = new FuncionarioDAO();
        f.setIdFuncionario(TelaLogin.idFunc);
        Object[] obj = {
            tabelaOrigem.getValueAt(tabelaProdutos.getSelectedRow(), 0), // id
            tabelaOrigem.getValueAt(tabelaProdutos.getSelectedRow(), 1), // nome produto
            1, // quantidade
            tabelaOrigem.getValueAt(tabelaProdutos.getSelectedRow(), 4), // tarja
            tabelaOrigem.getValueAt(tabelaProdutos.getSelectedRow(), 5), // preco
            tabelaOrigem.getValueAt(tabelaProdutos.getSelectedRow(), 6), // validade
            tabelaOrigem.getValueAt(tabelaProdutos.getSelectedRow(), 8), // farmacia
            dao.nomeFuncionario(f)
        };
        tabelaDestino.addRow(obj);
    }
    public void Listar() {
        try {
            ProdutoDAO dao = new ProdutoDAO();
            Farmacia far = new Farmacia();
            far.setIdFarmacia(TelaLogin.idFar);
            List<Produto> listaDeProdutos = dao.listarMedicamentos(far);
            DefaultTableModel modelo = (DefaultTableModel) tabelaProdutos.getModel();
            modelo.setNumRows(0);
            
            for (Produto p: listaDeProdutos) {
                modelo.addRow(new Object[] {
                    p.getIdProduto(),
                    p.getNomeProduto(),
                    p.getFornecedor(),
                    p.getQuantidade(),
                    p.getTarja(),
                    p.getPreco(),
                    new SimpleDateFormat("dd/MM/yyyy").format(p.getDataValidade()),
                    new SimpleDateFormat("dd/MM/yyyy").format(p.getDataFabricacao()),
                    p.getFarmacia().getNomeFarmacia(),
                });
            }
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        
    }
    private void menuReservadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReservadosActionPerformed
        
    }//GEN-LAST:event_menuReservadosActionPerformed

    private void menuReservadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReservadosMouseClicked
        ConsultarReservados cr1 = new ConsultarReservados();
        pane.add(cr1);
        cr1.setVisible(true);
    }//GEN-LAST:event_menuReservadosMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Listar();
    }//GEN-LAST:event_formWindowActivated

    private void btnCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarrinhoActionPerformed
        if (tabelaProdutos.getSelectedRowCount() != 0) {
            String tarja = String.valueOf(tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 4).toString());
            if (tarja.equals("Tarja preta") || tarja.equals("Tarja vermelha (com retenção da receita)")) {
                LiberarMedicamento lm = new LiberarMedicamento();
                pane.add(lm);
                lm.setVisible(true);

            } else {
                adicionarCarrinho();

            }
        } else {
            new nenhumaLinha(null, true).setVisible(true);
        }
    }//GEN-LAST:event_btnCarrinhoActionPerformed

    private void btnCarrinho02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarrinho02ActionPerformed
        pane.add(car);
        car.setVisible(true);
    }//GEN-LAST:event_btnCarrinho02ActionPerformed

    private void campoNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNomeKeyReleased
        if (evt.getKeyCode() != KeyEvent.VK_ALPHANUMERIC) {
            Buscar(campoNome.getText());
        }
    }//GEN-LAST:event_campoNomeKeyReleased

    private void campoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeActionPerformed

    private void btnProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarActionPerformed
        ConsultarFarmacias cf = new ConsultarFarmacias();
        pane.add(cf);
        cf.setVisible(true);
    }//GEN-LAST:event_btnProcurarActionPerformed

     public void Buscar(String nome) {
        try {
            Farmacia far = new Farmacia();
            far.setIdFarmacia(TelaLogin.idFar);
            ProdutoDAO dao = new ProdutoDAO();
            List<Produto> listaDeProdutos = dao.buscarProduto(nome, far);
            DefaultTableModel modelo = (DefaultTableModel) tabelaProdutos.getModel();
            modelo.setNumRows(0);
            Funcionario f = new Funcionario();
            FuncionarioDAO daof = new FuncionarioDAO();
            f.setIdFuncionario(TelaLogin.idFunc);
            for (Produto p: listaDeProdutos) {
                modelo.addRow(new Object[] {
                    p.getIdProduto(),
                    p.getNomeProduto(),
                    p.getFornecedor(),
                    p.getQuantidade(),
                    p.getTarja(),
                    p.getPreco(),
                    new SimpleDateFormat("dd/MM/yyyy").format(p.getDataValidade()),
                    new SimpleDateFormat("dd/MM/yyyy").format(p.getDataFabricacao()),
                    p.getFarmacia().getNomeFarmacia(),
                });
            }
        } catch (Exception e) {
            System.out.println("erro" + e);
            e.printStackTrace();
        }
    }
    public static void limparTabela(JTable table) {
        DefaultTableModel tabela = (DefaultTableModel) table.getModel();
        for (int i = tabela.getRowCount() -1; i >= 0 ; i--) {
            tabela.removeRow(i);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFarmaceutico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaFarmaceutico().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JButton btnCarrinho;
    private javax.swing.JButton btnCarrinho02;
    private javax.swing.JButton btnProcurar;
    private javax.swing.JTextField campoNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuReservados;
    public static javax.swing.JDesktopPane pane;
    public static javax.swing.JTable tabelaProdutos;
    // End of variables declaration//GEN-END:variables

   
}
